name: 发布
on: [push] #在推送的时候运行此action

jobs:
  deploy_job:
    runs-on: ubuntu-latest  #运行环境
    name: deploy
    steps:
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ vars.IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.TENGXUNYUN }} #引用之前创建好的secret
          local_path: './public/*'  # 对应我们项目build的文件夹路径
          remote_path: '/usr/share/nginx/html/'
